# https://hub.docker.com/_/microsoft-dotnet-sdk
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY netcore_webapi.csproj .
RUN dotnet restore

# copy everything else and build app
COPY . .
RUN dotnet publish netcore_webapi.csproj -c release -o /publish --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "netcore_webapi.dll"]

