name: ReactJS CI to Azure App Service

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'MyReactWithGitHubActions'
  AZURE_WEBAPP_PACKAGE_PATH: './Docker/hello-world-react'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout'
      uses: actions/checkout@main

    # login to Azure
    - uses: Azure/login@v2.1.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4.0.3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ./Docker/hello-world-react

    # deploy web app using Azure Credentials
    - uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./Docker/hello-world-react/build
        
    # Azure logout
    - name: logout
      run: |
        az logout
