name: ReactJS Docker Image CI to Azure Container Registry

on:
  workflow_dispatch:

env:
  ACR_NAME: 'ojedbubdockercontainers'
  ACR_REPO: 'helloworldreact'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: Azure/login@v2.1.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v2.0.0
      with:
        inlineScript: |
          az acr login --name ${{ env.ACR_NAME }}

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPO }}:${{ github.sha }} ./Docker/hello-world-react
        
    - name: Push Docker image to ACR
      run: |
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPO }}:${{ github.sha }}
        
